/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginErrorPanel.java
 *
 * Created on Mar 25, 2010, 12:36:38 PM
 */

package co.th.aten.hospital.ui;

/**
 *
 * @author Aten
 */
public class LoginErrorPanel extends javax.swing.JPanel {

    
    /** Creates new form LoginErrorPanel */
    public LoginErrorPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 24, 24));
        jLabel1.setText("Login fail ,please try again.");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
